(deftheme dracula-custom
  "Created 2022-11-27.")

(custom-theme-set-faces
 'dracula-custom
 '(cursor ((t (:background "#ccccc7"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#ff79c6"))))
 '(highlight ((t (:foreground "#ccccc7" :background "#464752"))))
 '(region ((t (:extend t :inherit (match)))))
 '(shadow ((t (:foreground "#6272a4"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:extend t :background "yellow1")) (((class color) (min-colors 88) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:extend t :background "yellow")) (((class color) (min-colors 16) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 8)) (:extend t :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((t (:background "#ffb86c"))))
 '(font-lock-builtin-face ((t (:slant italic :foreground "#8be9fd"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (shadow)))))
 '(font-lock-comment-face ((t (:inherit (shadow)))))
 '(font-lock-constant-face ((t (:foreground "#bd93f9"))))
 '(font-lock-doc-face ((t (:foreground "#6272a4"))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-function-name-face ((t (:weight bold :foreground "#50fa7b"))))
 '(font-lock-keyword-face ((t (:foreground "#ff79c6" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#8be9fd"))))
 '(font-lock-preprocessor-face ((t (:foreground "#ffb86c"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#8be9fd"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#bd93f9"))))
 '(font-lock-string-face ((t (:foreground "#f1fa8c"))))
 '(font-lock-type-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-variable-name-face ((t (:foreground "#d8a5f8" :weight bold))))
 '(font-lock-warning-face ((t (:background "#373844" :inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#8be9fd"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#b6b6b2" :background "#000000"))))
 '(header-line ((t (:inherit 'mode-line))))
 '(tooltip ((t (:foreground "#f8f8f2" :background "#44475a"))))
 '(mode-line ((t (:box (:line-width (1 . 1) :color "#44475a" :style nil) :inverse-video nil :foreground "#f8f8f2" :background "#44475a"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((supports :box t) (class color) (min-colors 88)) (:box (:line-width (2 . 2) :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width (1 . 1) :color "#373844" :style nil) :inverse-video nil :foreground "#b6b6b2" :background "#282a36"))))
 '(isearch ((t (:weight bold :inherit (match)))))
 '(isearch-fail ((t (:foreground "#282a36" :background "#ffb86c"))))
 '(lazy-highlight ((t (:foreground "#e2e2dc" :background "#373844"))))
 '(match ((t (:foreground "#282a36" :background "#f1fa8c"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#000000" :foreground "#F8F8F2" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 113 :width normal :family "Iosevka")))))

(provide-theme 'dracula-custom)
